version: 0.2

phases:
  install:
    commands:
      - "./tools/setup"
  build:
    commands:
      - "./tools/build"

artifacts:
  base-directory: "build"
  files:
    - "**/*"

cache:
  paths:
    - "node_modules/**/*"
