version: 0.2

env:
  variables:
    ENV: "prod"

phases:
  install:
    commands:
      - "./tools/setup frontend"
  build:
    commands:
      - "./tools/test frontend"
      - "./tools/build frontend"

artifacts:
  base-directory: "frontend/build"
  files:
    - "**/*"

cache:
  paths:
    - "frontend/node_modules/**/*"
