version: 0.2

phases:
  env:
    variables:
      ENV: "prod"
  install:
    commands:
      - "./tools/setup"
  build:
    commands:
      - "./tools/test"
      - "./tools/build"

artifacts:
  base-directory: "frontend/build"
  files:
    - "**/*"

  base-directory: "backend"
  files:
    - "**/*"

cache:
  paths:
    - "frontend/node_modules/**/*"
    - "backend/node_modules/**/*"
