version: 0.2

env:
  variables:
    ENV: "prod"

phases:
  install:
    commands:
      - "./tools/setup backend"
  build:
    commands:
      - "./tools/test backend"

cache:
  paths:
    - "backend/node_modules/**/*"
