version: 0.2

phases:
  install:
    commands:
      - "./tools/setup"
  build:
    commands:
      - "./tools/build"

artifacts:
  base-directory: "frontend/build"
  files:
    - "**/*"

cache:
  paths:
    - "frontend/node_modules/**/*"
    - "backend/node_modules/**/*"
