version: 0.2

phases:
  env:
    variables:
      ENV: "prod"
  install:
    commands:
      - "./tools/setup"
  build:
    commands:
      - "./tools/test"
      - "./tools/build"

artifacts:
  secondary-artifacts:
    frontend:
      base-directory: "frontend/build"
      files:
        - "**/*"
    backend:
      base-directory: "backend"
      files:
        - "**/*"

cache:
  paths:
    - "frontend/node_modules/**/*"
    - "backend/node_modules/**/*"
