#!/usr/bin/env bash
set -e

if [[ $# -eq 0 || $1 == "domain" ]]; then
  npx tap test/domain
fi

if [[ $# -eq 0 || $1 == "browser" ]]; then
  npx karma start
fi

if [[ $# -eq 0 || $1 == "backend" ]]; then
  npx tap test/backend
fi
